name: Release Build

on:
  release:
    types: [published]

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入 Release
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build shadowJar
        run: ./gradlew shadowJar

      - name: Upload Package to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}